// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTb5oWFIAbMlvYEfJmGk0j1s-RlvmjlW0',
    appId: '1:599344240437:web:2da269e8f87f91b4fd1e7c',
    messagingSenderId: '599344240437',
    projectId: 'jendela-dunia-61c3a',
    authDomain: 'jendela-dunia-61c3a.firebaseapp.com',
    storageBucket: 'jendela-dunia-61c3a.firebasestorage.app',
    measurementId: 'G-R40FD62QX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh5ExcFlDxyIS4mZB9DkygoqmpMZY2w1c',
    appId: '1:599344240437:android:8f5e979055489e40fd1e7c',
    messagingSenderId: '599344240437',
    projectId: 'jendela-dunia-61c3a',
    storageBucket: 'jendela-dunia-61c3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuS-N5XSilv1FASFAfclP4wJpyejRRvTo',
    appId: '1:599344240437:ios:ed788c41a93374f7fd1e7c',
    messagingSenderId: '599344240437',
    projectId: 'jendela-dunia-61c3a',
    storageBucket: 'jendela-dunia-61c3a.firebasestorage.app',
    iosBundleId: 'com.example.posyanduMob',
  );
}
